#
#  TMList (c) 2023 by Mikhail Kondrashin (mkondrashin@gmail.com)
#  Copyright under MIT Lincese. Please see LICENSE file for details
#
#  build_release.yml - github action to generate release files and upload image to Docker Hub
#

name: Go
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
    - uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v3

    - name: Check Go version
      run: go version
    
    - name: Tests
      run: go test -v ./...

    - name: Build TMList Windows
      run: GOOS=windows GOARCH=amd64 go build ./cmd/tmlist

    - name: Build Detect Windows
      run: GOOS=windows GOARCH=amd64 go build ./cmd/detect
      
    - name: Pack Windows
      uses: montudor/action-zip@v1
      with:
        args: zip tmlist_win64.zip tmlist.exe detect.exe

    - name: Build TMList Linux
      run: GOOS=linux GOARCH=amd64 go build ./cmd/tmlist

    - name: Build Detect Linux
      run: GOOS=linux GOARCH=amd64 go build ./cmd/detect

    - name: Pack Linux
      uses: montudor/action-zip@v1
      with:
        args: zip tmlist_linux64.zip tmlist detect

    - name: Build TMList macOS x86
      run: GOOS=darwin GOARCH=amd64 go build ./cmd/tmlist

    - name: Build Detect macOS x86
      run: GOOS=darwin GOARCH=amd64 go build ./cmd/detect

    - name: Pack macOS x86
      uses: montudor/action-zip@v1
      with:
        args: zip tmlist_macosx86.zip tmlist detect

    - name: Build TMList macOS ARM
      run: GOOS=darwin GOARCH=arm64 go build ./cmd/tmlist

    - name: Build Detect macOS ARM
      run: GOOS=darwin GOARCH=arm64 go build ./cmd/tmlist
      
    - name: Pack macOS ARM
      uses: montudor/action-zip@v1
      with:
        args: zip tmlist_macosxm.zip tmlist detect

    - name: Release 
      if: startsWith(github.ref, 'refs/tags/')
      uses: softprops/action-gh-release@v1
      with:
        files: |
          tmlist_win64.zip
          tmlist_linux64.zip
          tmlist_macosx86.zip
          tmlist_macosxm.zip

    - name: Build for Alpine
      run: CGO_ENABLED=0 GOOS=linux GARCH=amd64 go build ./cmd/tmlist

    - name: Log in to Docker Hub
      uses: docker/login-action@v2
      if: startsWith(github.ref, 'refs/tags/')
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_PASSWORD }}
    
    - name: Extract metadata (tags, labels) for Docker
      uses: docker/metadata-action@v4
      if: startsWith(github.ref, 'refs/tags/')
      id: meta
      with:
        images: mpkondrashin/tmlist
    
    - name: Build and push Docker image
      uses: docker/build-push-action@v3
      if: startsWith(github.ref, 'refs/tags/')
      with:
        context: .
        push: true
        tags: ${{ steps.meta.outputs.tags }}
        labels: ${{ steps.meta.outputs.labels }}
